# Generated by Django 5.1.1 on 2024-09-16 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('excerpt', models.TextField(blank=True, max_length=256)),
                ('school', models.IntegerField(choices=[(0, 'Astromancy'), (1, 'Chronomancy'), (2, 'Conjuration'), (3, 'Destruction'), (4, 'Divination'), (5, 'Enchantment'), (6, 'Illusion'), (7, 'Necromancy'), (8, 'Protection'), (9, 'Restoration'), (10, 'Transmutation')], default=0)),
                ('ap_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('mp_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('range', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('concentration', models.BooleanField()),
                ('description', models.TextField(unique=True)),
                ('ap_enhancements', models.TextField(blank=True)),
                ('mp_enhancemnets', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homebrew_spell_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
