# Generated by Django 5.1.1 on 2024-09-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='mp_enhancemnets',
            new_name='mp_enhancements',
        ),
    ]
